import { test } from 'node:test';
import assert from 'node:assert/strict';
import jwt from 'jsonwebtoken';
import { createApp } from './app.js';
import { openDatabase } from './db.js';
const env={JWT_SECRET:'test-secret-only-0123456789-0123456789',APP_URL:'https://capsule.example',GITHUB_CLIENT_ID:'test-id',GITHUB_CLIENT_SECRET:'test-secret'};
function token(id){return jwt.sign({login:`user${id}`},env.JWT_SECRET,{algorithm:'HS256',issuer:'ai-capsule',audience:'ai-capsule-web',subject:`github:${id}`,expiresIn:'8h'});}
async function withServer(run,options={}){const db=openDatabase(':memory:');const server=createApp({db,env,...options}).listen(0);try{await new Promise(r=>server.once('listening',r));await run(`http://127.0.0.1:${server.address().port}`)}finally{server.close();db.close()}}
const record={project_name:'SmartFarm',prompt_title:'Debug API',prompt_version:'v1',prompt_text:'How can I debug this?',response_summary:'Check the logs',category:'Coding',usefulness:'Good',reviewed:true,improved:false,screenshot_url:'',notes:'Verified locally'};
test('health, unauthenticated and fake cookie',()=>withServer(async base=>{assert.deepEqual(await (await fetch(base+'/api/health')).json(),{status:'ok'});for(const cookie of ['', 'token=fake-token-123']){const r=await fetch(base+'/api/capsules',{headers:{cookie}});assert.equal(r.status,401)}}));
test('owner-scoped CRUD and server-assigned identity',()=>withServer(async base=>{const call=(path,id,options={})=>fetch(base+path,{...options,headers:{cookie:`token=${token(id)}`,'Content-Type':'application/json',...options.headers}});let r=await call('/api/capsules',1,{method:'POST',body:JSON.stringify({...record,user_id:'github:2'})});assert.equal(r.status,201);const created=await r.json();assert.equal(created.user_id,'github:1');assert.equal((await (await call('/api/capsules',2)).json()).length,0);assert.equal((await call(`/api/capsules/${created.id}`,2,{method:'PUT',body:JSON.stringify(record)})).status,404);assert.equal((await call(`/api/capsules/${created.id}`,2,{method:'DELETE'})).status,404);r=await call(`/api/capsules/${created.id}`,1,{method:'PUT',body:JSON.stringify({...record,prompt_title:'Improved prompt'})});assert.equal((await r.json()).prompt_title,'Improved prompt');assert.equal((await call(`/api/capsules/${created.id}`,1,{method:'DELETE'})).status,200);assert.deepEqual(await (await call('/api/capsules',1)).json(),[])}));
test('rejects malformed content, forbidden origin and token with wrong audience',()=>withServer(async base=>{const cookie=`token=${token(1)}`;let r=await fetch(base+'/api/capsules',{method:'POST',headers:{cookie,'Content-Type':'application/json'},body:JSON.stringify({...record,project_name:''})});assert.equal(r.status,400);r=await fetch(base+'/api/capsules',{method:'POST',headers:{cookie,origin:'https://attacker.example','Content-Type':'application/json'},body:JSON.stringify(record)});assert.equal(r.status,403);const wrong=jwt.sign({},env.JWT_SECRET,{subject:'github:1',audience:'wrong',issuer:'ai-capsule'});assert.equal((await fetch(base+'/api/capsules',{headers:{cookie:`token=${wrong}`}})).status,401)}));
test('OAuth checks state, reads GitHub ID, issues Secure HttpOnly token',()=>withServer(async base=>{const r=await fetch(base+'/auth/github/start',{redirect:'manual'});assert.equal(r.status,302);const cookies=r.headers.getSetCookie();assert.match(r.headers.get('location'),/code_challenge_method=S256/);const state=new URL(r.headers.get('location')).searchParams.get('state');const cookieHeader=cookies.map(c=>c.split(';')[0]).join('; ');assert.equal((await fetch(base+'/auth/github/callback?code=test&state=wrong',{headers:{cookie:cookieHeader}})).status,400);const callback=await fetch(base+`/auth/github/callback?code=test&state=${state}`,{headers:{cookie:cookieHeader},redirect:'manual'});assert.equal(callback.status,302);const issued=callback.headers.getSetCookie().find(c=>c.startsWith('token='));assert.match(issued,/Secure/);assert.match(issued,/HttpOnly/);assert.match(issued,/SameSite=Lax/);const sessionCookie=issued.split(';')[0];assert.deepEqual(await (await fetch(base+'/api/me',{headers:{cookie:sessionCookie}})).json(),{login:'student'});},{githubFetch:async url=>({ok:true,json:async()=>url.includes('access_token')?{access_token:'provider-token'}:{id:42,login:'student'}})}));
